### ISSUE TITLE
Creates a timer when sending msg.stopTimer

### ISSUE THREAD

**Issue by jbardi** [krencl/node-red-contrib-delay-topic-message#1]
If I send msg.stopTimer when there is no current timer running under that topic, it should simply ignore it, but instead it creates a timer and ignores the stopTimer instead.

In my project there is no way to know if a timer is currently running under that topic, so I default to sending msg.stopTimer on all of those request to ensure if one does exist it will be stopped, but currently, that is not the case, as it is only acting on the stopTimer if a timer already exists.

Hopefully this can be fixed soon, otherwise I'm going to have to find another node that can operate timers on specific topics.

**Comment by krencl** [comment]
Hi, thank you for bug report.

It is fixed now, it should be updated in node-red registry soon as version v1.2.0
