### ISSUE TITLE
How does this node work?

### ISSUE THREAD

**Issue by jprasm** [krencl/node-red-contrib-delay-topic-message#2]
Hi there, 
I cannot seem to get this node to work as described. It seems to be a timer that simply passes the msg after the set time. I cannot get the message to be discarded. Can we get better instructions?

**Comment by krencl** [comment]
I updated description little bit. Usage of this node is delivering only last message within topic in defined time interval. For example: You have node with 5 seconds delay. Now, if you will send 3 messages in one topic within 1 second, delivered will be only last one.

You can try it with timestamp inject.

![image](https://user-images.githubusercontent.com/1188924/148824664-4f7d053b-39c5-4c8c-a98b-18e27da83908.png)
