### ISSUE TITLE
Improvement suggestion: Stop all timers

### ISSUE THREAD

**Issue by WombatHollow** [krencl/node-red-contrib-delay-topic-message#3]
If you want to stop all timers, then send msg.stopTimer with msg.topic = "all".   This will stop all timers without having to know the topic of the timers.   Could also be implemented using another trigger like msg.clear or msg.reset.
Thanks

**Comment by krencl** [comment]
Hi, thanks for idea. I think I can implement this, only problem is keyword "all" for topic - that could be regular name of topic. 
Sending `msg.clearAll = true` will work.

**Comment by WombatHollow** [comment]
Not critical as to keyword, but boolean true works.   Pick all as that was
used in the multiple queue node.

**Comment by krencl** [comment]
Update was released
https://github.com/krencl/node-red-contrib-delay-topic-message/releases/tag/v1.3.1
https://flows.nodered.org/node/node-red-contrib-delay-topic-message
