### ISSUE TITLE
Improvement/feature request - Per topic delay

### ISSUE THREAD

**Issue by MStcz** [krencl/node-red-contrib-delay-topic-message#5]
Hi, I have one more suggestion, implementation of **Per topic delay**.

This msg would be delayed by 60 second, default timer for other topics not affected:
```
{
    "payload": "test_msg1",
    "topic": "msg1",
    "delayTopic" : 60
}
```

This msg would be delayed by 120 second, default timer for other topics not affected:
```
{
    "payload": "test_msg2",
    "topic": "msg2",
    "delayTopic" : 120
}
```

**Comment by krencl** [comment]
Hi, I think, this is working with already implemented `msg.delay` as I looking to source code (can't test it now).

You just need to add `delay` property to _every message within topic_, then it will work as you described.

**Comment by MStcz** [comment]
Hi @krencl, you are right, `msg.delay` rewriting delay timer just for the message where the delay was changed. The default one on the node remain unaffected. Thank you for the quick response and sorry for confusing.
